import User, { ROLE } from '#models/user'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class UserSeeder extends BaseSeeder {
  async run() {
    await User.createMany([
      {
        email: 'guilfred@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.SUPER_ADMIN,
        isEnabled: true,
        name: 'Guillaume',
        firstname: 'Alfred',
        phone: null,
        description: 'Compte Super admin',
        ville: 'Abidjan',
        codePostal: null,
        address: 'Test jjjdeooo',
      },
      {
        email: 'william@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.AGENT,
        isEnabled: true,
        name: 'Henry',
        firstname: 'William',
        phone: null,
        description: 'Compte agent',
        ville: 'Paris',
        codePostal: '10380',
        address: 'Test jjjdeooo',
      },
      {
        email: 'pietrus.emmanuel@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.AGENT,
        isEnabled: true,
        name: 'Pietrus',
        firstname: 'Emmanuel',
        phone: null,
        description: 'Compte agent',
        ville: 'Nanterrre',
        codePostal: '30090',
        address: 'Test Nanterrre',
      },
      {
        email: 'marvin.finley@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.AGENT,
        isEnabled: true,
        name: 'Finley',
        firstname: 'Marvin',
        phone: null,
        description: 'Compte agent',
        ville: 'Montpelier',
        codePostal: '56098',
        address: 'montpelier',
      },
      {
        email: 'fred.perry@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.TELE_VENDEUR,
        isEnabled: true,
        name: 'Perry',
        firstname: 'Fred',
        phone: null,
        description: 'Compte télévendeur',
        ville: 'Casablanca',
        codePostal: '20000',
        address: 'adreess test',
      },
      {
        email: 'esso.emmanuel@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.TELE_ADMIN,
        isEnabled: true,
        name: 'Esso',
        firstname: 'Armel',
        phone: null,
        description: 'Compte Admin télévendeur',
        ville: 'Casablanca',
        codePostal: '20000',
        address: 'adreess test',
      },
      {
        email: 'thierry.ladeux@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.ADMIN,
        isEnabled: true,
        name: 'ladeux',
        firstname: 'Thierry',
        phone: null,
        description: 'Compte Admin',
        ville: 'Paris',
        codePostal: '51292',
        address: 'adreess test',
      },
      {
        email: 'pdanet@mail.test',
        password: 'P@ssw0rd',
        role: ROLE.USER,
        isEnabled: true,
        name: 'Danet',
        firstname: 'Patricia',
        phone: null,
        description: 'Compte Utilisateur',
        ville: 'Paris',
        codePostal: '41298',
        address: 'adreess test',
      },
    ])
  }
}
